name: workflow
on: [push]
jobs:
  job:
    runs-on: ubuntu-latest
    container: node:lts
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Prepare
        run: npm ci
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
